### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [POlONM/QuaternionJAVA#1]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

Игнорируемые файлы также необходимо удалить из удаленного репозитория (иначе git будет продолжать отслеживать изменения в них). Для этого можно воспользоваться командой [git-clean](https://git-scm.com/docs/git-clean).

**Comment by JohnKhandygo** [comment]
Здесь мой косяк, не та команда. Инструкцию для удаления игнорируемых файлов из удаленного репозитория смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by JohnKhandygo** [comment]
Не все project specific файлы добавлены в .gitignore.

**Comment by JohnKhandygo** [comment]
Замечательно. Два момента:
- [x] С чего бы игнорировать что-либо, расположенное в папке с исходным кодом программы?
- [ ] Игнорируемые файлы все еще в удаленном репозитории. Их необходимо удалить. Подробную инструкцию смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками в предыдущем комментарии, актуально.

**Comment by POlONM** [comment]
@JohnKhandygo 
Папка ".idea" не удаляется с репозитория.
